[package]
name = "taskbar"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "*", features = ["image"] }
lnk = "*"
dirs = "*"
pelite = "*"
windows = { version = "0.52.0", features = ["Win32_UI", "Win32_System", "Win32_UI_WindowsAndMessaging", "Win32_System_Threading"] }